### ISSUE TITLE
HolonicSystems-Free

### ISSUE THREAD

**Issue by hdavid** [VCVRack/library#525] opened 2018-10-25 09:39 UTC
Hi VCV Rack Team,

we have put together a plugin we would like you to release on the plugins page.

The commit id of the last version is ba81886c4092c35d0c8d2838886e3dd932d5a8f0 
And the repo is located at : https://github.com/hdavid/VCVRack-Holon.ist.git

At the moment we depend on Bonjour on MacOS, but it works out of the box no need to include any external lib/headers while using the standard SDK and build toolchain you provide.
However in the future we would like to support mDNS on Linux (most likely using Avahi) and Win64 (not sure about which lib we will use there). Do you have some advice on the approach to take there ?

And here Manifest :
```
{
  "name": "Holonic Systems - Free",
  "author": "Holonic Systems",
  "license": "CC0 1.0",
  "pluginUrl": "https://github.com/hdavid/VCVRack-Holon.ist",
  "authorUrl": "https://holonic.systems/",
  "authorEmail": "henri@holonic.systems",
  "manualUrl": "https://github.com/hdavid/VCVRack-Holon.ist/blob/master/README.md",
  "sourceUrl": "https://github.com/hdavid/VCVRack-Holon.ist.git",
  "latestVersion": "0.6.0",
  "status": "available"
}
```

Thanks a lot in advance

**Comment by cschol** [comment] 2018-10-25 12:11
Thank you for submitting your plugin.

~~I filed one issue (https://github.com/hdavid/VCVRack-Holon.ist/issues/1) related to logging, which needs to be resolved before it can be included in the Plugin Manager.~~ **Resolved.**

In general, the plugins distributed via the Plugin Manager have be available and **buildable** for all 3 platforms (Windows, GNU Linux, macOS) from the same source via `make`. 

If you need special libraries your plugin to work, which are not provided by the Rack runtime, the plugin must provide the libraries at build **and** at runtime. `git submodules` are a good way to get external source code integrated in the plugin source tree. A `make dep` target is a canonical way to build dependencies for the plugin as part of the build process. For example, the [Fundamental](https://github.com/VCVRack/Fundamental) plugin uses `libsamplerate` as an external dependency (does not use `make dep`, but it is a simple example of how to integrate an external library).

Lastly, please pay attention to licensing issues with libraries you provide with your plugin.

**Comment by AndrewBelt** [comment] 2018-10-25 15:33
Yes, all plugins need to build on all three platforms to be added to the plugin manager. You can be added to the list, but it won't have an Add button.

**Comment by hdavid** [comment] 2018-10-25 15:45
Hi Andrew, it does build on windows mac and Linux at the moment :)
Please let me know if it does not in your build tool chain.

**Comment by cschol** [comment] 2018-10-25 15:46
Thanks for resolving the logging issues. I have integrated the plugin. Andrew will let us know if there are issues with the official tool chain and we go from there.

**Comment by AndrewBelt** [comment] 2018-10-25 20:29
Build fails on (at least) Linux.

```cpp
src/MdnsServer.hpp:17:33: fatal error: avahi-client/client.h: No such file or directory
 #include <avahi-client/client.h>
```
If not immediately fixable, could @cschol remove the submodule from `repos/`?

**Comment by hdavid** [comment] 2018-10-25 20:32
I will fix that in the next hour !  Sorry about that !

**Comment by cschol** [comment] 2018-10-25 22:32
@AndrewBelt See if this fixes it. If not, I'll remove the submodule.

**Comment by AndrewBelt** [comment] 2018-10-25 23:03
Two issues on Mingw: Your Makefile needs to use
```Makefile
include $(RACK_DIR)/arch.mk
ifdef ARCH_WIN
```
instead of the `$(OS)` thing.

Also, 
```
x86_64-apple-darwin15-clang++-libc++  -std=c++11 -stdlib=libc++  -DSLUG=HolonicSystems-Free -fPIC -I/home/vortico/src/VCV/community/Rack-SDK/include -I/home/vortico/src/VCV/community/Rack-SDK/dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/HolonicSystems-Free.cpp.o src/HolonicSystems-Free.cpp
src/MdnsServer.cpp:254:3: error: use of undeclared identifier 'htons'
                htons(port), // port number
                ^
```

**Comment by hdavid** [comment] 2018-10-26 06:43
Hi, 

Thanks

Fixed all `#ifdef` to `ARCH_LIN`, `ARCH_WIN `or `ARCH_MAC`. also tested it still compiled fine on all three architectures.

**Comment by cschol** [comment] 2018-10-26 09:00
I pulled in this latest update. I am wondering though why we get different results between his system and the official build system.

**Comment by AndrewBelt** [comment] 2018-10-26 17:21
Nothing was done about the error above, skipping build.

No, it is not easy to install my toolchain.

**Comment by cschol** [comment] 2018-10-26 17:37
Remove the submodule for now and leave the manifest?

**Comment by AndrewBelt** [comment] 2018-10-26 17:43
My memory is fuzzy, but perhaps just an include header is needed?

**Comment by cschol** [comment] 2018-10-26 17:45
Is the build error on WIndows or macOS?

**Comment by cschol** [comment] 2018-10-26 17:49
`htons` is defined in `src/byteorder.h`. I don't see it included in `MdnsServer.cpp`. Maybe that's it?

**Comment by hdavid** [comment] 2018-10-26 18:42
hi, 

The error was there : https://github.com/hdavid/VCVRack-Holon.ist/blob/master/src/MdnsServer.cpp#L253
this line was wrongly included because of the dubious #ifdef 

this should be fixed, and this section properly excluded for Linux and Mac, with this commit : be2e6bb2d56cda7d939ea90bf9aaa14977c269ff
https://github.com/hdavid/VCVRack-Holon.ist/commit/be2e6bb2d56cda7d939ea90bf9aaa14977c269ff

**Comment by hdavid** [comment] 2018-10-30 10:37
Hi @cschol ,

I believe we fixed all the standing issues, and the plugin has been tested on Windows, Mac and Linux.
Do you think we could get this released this week on the plugins page ?

the last commit is 62836327dfff73e9567c758491b3bffb34610573

cheers,

Henri

**Comment by cschol** [comment] 2018-11-01 03:04
@AndrewBelt Have you had a chance to try this latest version?

**Comment by AndrewBelt** [comment] 2018-11-01 06:11
Still

```
src/MdnsServer.cpp:253:3: error: use of undeclared identifier 'htons'
                htons(port), // port number
                ^
```
on Mac.

**Comment by AndrewBelt** [comment] 2018-11-02 00:55
`htohs` is defined in arpa/inet.h on Mac. You need to add that include header to MdnsServer.cpp or hpp.

**Comment by hdavid** [comment] 2018-11-02 07:33
Hi Andrew,

Thanks a lot for providing the error message. I am actually confused as for why it did compile on my machine without complaining though. With such kind of error it should not compile anywhere. Maybe because  the option `-undefined dynamic_lookup`  in `plugin.mk` ?

anyhow thanks tracking that one down. i committed the fix : cdfd202cafc8dffd5f35affd6040d5444644f30f

**Comment by AndrewBelt** [comment] 2018-11-02 07:58
Some Mac SDKs allow noncompliant code, some don't. Had nothing to do with linking, it's in the compilation stagestage.

**Comment by AndrewBelt** [comment] 2018-11-03 01:18
Updated build

**Comment by hdavid** [comment] 2018-11-16 15:58
Hi,

i released a new version of the plugins. could you update the build ?
thanks a lot in advance.
the commit id is : 8095e57488417c54b27bde4dcd0c4eea158dbd78

cheers

**Comment by AndrewBelt** [comment] 2018-11-17 10:18
Updated build

**Comment by hdavid** [comment] 2018-12-12 13:59
Hi,

we released a new version of our plugins. could you include them in the build.
the last commit is 4c1a2e70aef5c650173f5c641229c4494dd8e174

the version is  0.6.2

thanks a lot in advance,

Henri

**Comment by AndrewBelt** [comment] 2019-01-12 05:18
Updated build

**Comment by hdavid** [comment] 2019-02-14 14:32
Hello,

We updated our plugins to include an 8 step sequencer, inspired by the a-155 / a-154

the version is bumped to 0.6.4 and commit hash is  06f60794377422d17e34121017a5abb768ccea23

thanks a lot

henri

**Comment by hdavid** [comment] 2019-04-11 15:28
Hello VCV Team !

We have updated our plugins and added a couple of modules too.
version: 0.6.4
commit hash : ac575192fd39bf3c0800ea784edb625bbeb15d52

thanks a lot in advance

Henri

**Comment by AndrewBelt** [comment] 2019-04-19 09:47
Was the version not bumped?

**Comment by hdavid** [comment] 2019-04-19 09:51
hi Andrew,

Previously submitted version was 0.6.3 and this version is 0.6.4, both in json and makefile are updated.
currently available version is 0.6.3 : https://vcvrack.com/plugins.html#holonic

or i am missing smth ?

cheers

henri

**Comment by AndrewBelt** [comment] 2019-04-19 09:55
Perhaps @cschol's commit didn't pull in that version?

**Comment by cschol** [comment] 2019-04-19 23:05
Weird, sorry about that. I'll check that when I get home.

**Comment by cschol** [comment] 2019-04-20 14:32
Fixed. Sorry about that.

**Comment by AndrewBelt** [comment] 2019-04-21 10:25
Updated build

**Comment by hdavid** [comment] 2019-04-21 12:08
thanks !

**Comment by hdavid** [comment] 2019-04-23 21:26
Hi, it's me again :)

Small bug fix in the quantiser needs to be released. Sorry about this.
version : 0.6.5
commit hash : 7491676db8308211591886994be665e0c8b32517
cheers

**Comment by AndrewBelt** [comment] 2019-04-28 01:59
Updated build

**Comment by hdavid** [comment] 2019-05-06 18:04
Hi,

Some bug fixes for quantiser. Could you update the build ?
version 0.6.6
commit hash : 759e483fef2eb90ee90c6f6f8cbefcb96c45aecd

thanks a lot in advance

**Comment by hdavid** [comment] 2019-06-12 19:49
Hi,

i made added a few features and bug fixes to our plugins.
new version is: 0.6.7
commit hash: af58b359be3097a316e757859a845df883ae9c0e

thanks a lot in advance

Henri

**Comment by cschol** [comment] 2019-06-16 21:46
Invalid tags in `plugin.json`: https://github.com/hdavid/VCVRack-Holon.ist/issues/8

**Comment by hdavid** [comment] 2019-06-19 18:55
Hi,

fixed
new version is: 0.6.7
commit hash: af58b359be3097a316e757859a845df883ae9c0e

for VCV Rack 1.0
branch: v1
version: 1.0.0
commit hash: d8519da26d114e2cfa811f9c1dd4cdbd36f06307

thanks a lot in advance

Henri

**Comment by hdavid** [comment] 2019-06-21 21:49
Hi,

While upgrading to 1.0, we made a mistake in the slugs and the slug of the our plugin suite was mistakenly changed. This leads to a duplicated entry in the list of plugins on the plugins page on VCV site and the inability to load old presets. Sorry about this.

Could you remove from the plugins page our plugins with slug 'HolonicSystemsFree' and only keep the entry 'HolonicSystems-Free'. I already committed a fix for this, the last version 1.0.1 is with commit hash 9e0146ea0188edcce68fef56ca01b11d64a157ff

If possible easily, it would be great for the users the users that registered 'HolonicSystemsFree' to be migrated to 'HolonicSystems-Free' so that they continue to receive future updates and can share patches with other users.

Sorry for the troubles and thanks a lot in advance !

Henri

**Comment by cschol** [comment] 2019-06-22 16:46
I integrated the new version 1.0.1. @AndrewBelt should look at the duplicate entry in the plugin manager list. I am not quite sure if that will be resolved automatically.

**Comment by AndrewBelt** [comment] 2019-06-22 17:18
Duplicate entry removed.

**Comment by hdavid** [comment] 2019-07-01 18:23
Hi Team,

Some minor fixes for our clock divider. 
Commit hash : 9d1d0c9d2739ef028539be8638c164388343b2a4

cheers,

henri

**Comment by hdavid** [comment] 2020-01-26 17:19
Hi,

A small bug fix for the Holonic Systems plugins !

the commit hash is: 2d64e00b3c292ac36be9e7d426f66ceaf4fe9acb
https://github.com/hdavid/VCVRack-Holon.ist/commit/2d64e00b3c292ac36be9e7d426f66ceaf4fe9acb
thanks a lot !

regards,

Henri

**Comment by hdavid** [comment] 2020-01-27 17:37
Hi Andrew,

thanks for handling this one so swiftly! there is seems to be something off with the plugins however.
i deleted the plugin, restarted rack. It then says there is an update. but it does not seem to download anything. i suppose maybe smth wrong with the json file. but i am not sure. 

any idea ?

cheers,

henri

**Comment by AndrewBelt** [comment] 2020-01-27 17:45
@hdavid What's your OS

**Comment by hdavid** [comment] 2020-01-27 17:48
macos catalina. do you think it could be a file case issue ?

**Comment by fractalgee** [comment] 2020-01-28 07:40
@AndrewBelt: On Windows 10 it tries to download it but reports that
download was unsuccessful in log file. Won't update no matter how often I
ask Rack to... Some others report it on Mac too, also file name of plugin
if it downloads seems wrong as it does not match what it downloads if it
does for some folks....

**Comment by AndrewBelt** [comment] 2020-01-28 17:08
Can't reproduce the issue on either of those OS's, need more information.

**Comment by Petervos2018** [comment] 2020-01-28 17:11
https://community.vcvrack.com/t/holonicsystems-1-03-update-not-working/7965/10

**Comment by AndrewBelt** [comment] 2020-01-28 17:33
Alright, here's what up. 852 users have the slug `HolonicSystemsFree` in their account, 18482 have `HolonicSystems-Free`.

I don't know why there are two slugs floating around, but *please do not ever change the slug of your plugin*, as it gives your plugin an entirely different identity. See [.slug](https://vcvrack.com/manual/Manifest#slug). In fact, if the slug is changed, we don't accept the update on VCV Library unless it slips by us.

So which slug is the correct one? How many patches contain `HolonicSystemsFree` vs `HolonicSystems-Free`? After we determine this, I can change all users to the correct slug.

**Comment by hdavid** [comment] 2020-01-28 17:49
Hi andrew,

Sorry about this ! i am not sure this happened.

i am not sure how this happened. i suppose we should use the one that used by most users and currently in the JSON file ? 
https://github.com/hdavid/VCVRack-Holon.ist/blob/master/plugin.json

therefore i would propose to stick to`HolonicSystems-Free`

i recall we already had an issue like that and we fixed back then. 
https://github.com/hdavid/VCVRack-Holon.ist/commit/4d6542049e6c2d0099bbdc81ea432288d0e6d706#diff-b3568fa08e53a00f66841ed9ca2c53d4
we currently are using the current slug that we fixed back then. i am not sure how these users showed up with the old slug :/

anyhow, thanks a million for your help !

**Comment by AndrewBelt** [comment] 2020-01-28 18:05
I don't see how it happened either, since we don't have a `HolonicSystemsFree` ZIP package on file, but we did have `HolonicSystemsFree` in the manifest library for some period of time.

Okay, all I've done is purged `HolonicSystemsFree` from the database. Users will need to add this plugin at https://vcvrack.com/plugins#Holonic%20Systems if it is not yet added to their account.

**Comment by fractalgee** [comment] 2020-01-28 18:08
my slug is HolonicSystems-Free in all patches used thus far (ex ancient mac
and modern AMD win10 system) for what it's worth

**Comment by fractalgee** [comment] 2020-01-28 18:10
@AndrewBelt, that fixed things here, so updated now, just FYI

**Comment by hdavid** [comment] 2020-01-28 21:59
Thanks @AndrewBelt  i can confirm it works just fine now !

**Comment by hdavid** [comment] 2020-03-31 18:51
Hi VCV Team !

We have a small bug fix for our plugin suite. Could you please update your configs to use this new commit hash ? f3b018d7f352731289b086283416778e24db81a0
https://github.com/hdavid/VCVRack-Holon.ist/commit/f3b018d7f352731289b086283416778e24db81a0

Thanks a lot in advance,

Henri

**Comment by hdavid** [comment] 2020-04-02 07:28
thank you Andrew !

**Comment by hdavid** [comment] 2020-04-07 06:00
Hi VCV Team,

As suggested by Andrew, here is a tiny update, just to remove the "- free" from the name of the plugin suite.
commit hash: 25340046a3ce270e38e13702a75ef850f20369e6

have a great day and stat safe :)

cheers,

henri

**Comment by hdavid** [comment] 2021-05-03 17:13
Hello VCV team, 
We have a small update for our plugins, could you be so kind to include it in the library ?
The commit hash to use is : 55c426198f7a205daae13d1df747ca962b5ad8a2
Thanks a lot !
Cheers,
Henri

**Comment by hdavid** [comment] 2021-05-11 16:28
Hi again VCV Team,

One of our user, right after my previous bug fix requested to implement Polyphonic on some of our modules. Sorry for the double work.

Could you use this commit: 
https://github.com/hdavid/VCVRack-Holon.ist/commit/4438d5b80f9b14cbba38627a74ae69f968142c5f

Kind Regards,

Henri

**Comment by hdavid** [comment] 2021-11-30 21:44
Hello VCV Rack Team!

Congratulation on releasing VCV Rack2 :)

We have updated and tested our plugins with VCV Rack 2 and are happy to share them with the community.
Could you update the build for to include this commit:
5fe1d9b68bb1fb8205308cd41a0be3ea1a019299
https://github.com/hdavid/VCVRack-Holon.ist/tree/v2

Cheers,

Henri

**Closed** 2021-12-01 00:50 UTC
Labels: plugin
