### ISSUE TITLE
dBiz

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/library#516] opened 2018-09-28 06:54 UTC
Author hasn't requested an update, but we can pull it ourselves.
https://github.com/dBiz/dBiz
0.6.1

**Comment by AndrewBelt** [comment] 2018-09-29 07:41
Updated build

**Comment by dBiz** [comment] 2019-06-21 07:54
dBiz plugins updated to 1.0.0

**Comment by cschol** [comment] 2019-06-21 12:45
Committed build directory/large repo size: https://github.com/dBiz/dBiz/issues/37
Invalid manifest entries: https://github.com/dBiz/dBiz/issues/38

**Comment by dBiz** [comment] 2019-06-21 19:28
manifest fixed and cleaned the repo ... i used the cleaner but not so sure of the result ... check it out ;) thx

**Comment by dBiz** [comment] 2019-06-26 06:07
Updated 
version 1.0.1
commit 3d6b1f6adfff7ea35ef705bbd241e435f84b3f80

hope I've done right ;)

**Comment by cschol** [comment] 2019-07-02 02:07
@AndrewBelt Is there any issues with this plugin?

**Comment by AndrewBelt** [comment] 2019-07-02 04:43
The repo's manifest version is not updated.

**Comment by Coirt** [comment] 2019-07-02 04:46
This is actually crashing the latest dev build for me, latest source and v1.1.0 dist.

Still trying to narrow it down. So have not reported an issue yet.

get an assertion `input ->portId != input2->portId`

**Comment by Coirt** [comment] 2019-07-02 05:13
Not too sure what module is causing rack to crash. Had copied the dist over to the dev build earlier on today. Because it was not recently built/installed/updated when entering the module browser the faulty module was not loaded. It was only when I keyed in F that it crashed. The only f's in dbiz are PerfMixer and FourSeq commenting these out still causes a crash.

Almost certain dBiz is the cause, only plugin in the folder. Can investigate further tomorrow.

**Comment by AndrewBelt** [comment] 2019-07-02 06:41
See https://community.vcvrack.com/t/rack-v1-development-blog/1149/526?u=vortico

**Comment by dBiz** [comment] 2019-07-02 07:01
Hi, i'm cleaning the code and fixing the inputs now

**Comment by dBiz** [comment] 2019-07-02 08:01
I've removed all the inputs and outputs from for{}  and made unique,
but still, crash... I press ignore just a couple of time and then the plugins works ...

I'll take a closer look to my ugly code;)

**Comment by dBiz** [comment] 2019-07-02 08:15
Works now on my dev build ;)

**Comment by Coirt** [comment] 2019-07-02 15:34
Yeah, latest not crashing for me also. 

@dBiz 
Manifest is still version 1.0.0

**Comment by dBiz** [comment] 2019-07-03 06:24
updated manifest too ;)

**Comment by dBiz** [comment] 2019-08-02 07:00
I've updated to 1.1.2 ;) manifest, makefile and more cleaned code,

**Comment by cschol** [comment] 2019-08-03 03:02
Compile failure: https://github.com/dBiz/dBiz/issues/44

**Comment by dBiz** [comment] 2019-08-03 11:11
Should be fine now ;)

**Comment by cschol** [comment] 2019-08-03 13:10
Still does not compile. Issue updated with patch.

**Comment by dBiz** [comment] 2021-12-01 21:25
dBiz modules are now ready for v2... sorry for being silent for a while ;) 
version 2.0.1
commit 3580d3297aed519a58cfec5c8c95dac1a4d886a6
https://github.com/dBiz/dBiz/tree/v2

**Comment by dBiz** [comment] 2021-12-17 18:13
dBiz 2.0.3 with font stuff fixed ;)

commit 552d8c2487e1f15e7a66b02b8f85e4cc7fed667e
https://github.com/dBiz/dBiz/tree/v2

**Comment by cschol** [comment] 2021-12-18 04:05
Something does not look right. The modules do not show any custom displays now. They are just black. Can you doublecheck the font code?

**Comment by dBiz** [comment] 2021-12-18 05:21
Hi, i've checked on my machines and works... I don't know, my coding skills are quite low =( 
![image](https://user-images.githubusercontent.com/12683589/146630210-55d25865-ca9d-4124-a09c-15d0334574ac.png)

**Comment by cschol** [comment] 2021-12-18 16:38
Dot matrix displays are not showing text on GNU/Linux platform: https://github.com/dBiz/dBiz/issues/52

**Comment by cschol** [comment] 2021-12-18 22:01
`plugin.dll` committed to repository: https://github.com/dBiz/dBiz/issues/53

**Comment by dBiz** [comment] 2021-12-22 18:38
.dll removed at commit 934524a548501a81796c3b9afb538036b6a771e1
https://github.com/dBiz/dBiz/tree/v2

**Comment by cschol** [comment] 2021-12-23 14:01
`plugin.dll` is still in the repository history. Please follow the instructions in https://github.com/dBiz/dBiz/issues/53 to remove it (using BFG Repo-Cleaner).

**Comment by dBiz** [comment] 2022-08-18 08:01
Updated fonts and fixed dual filter at commit ec7bcd9fecd21db4bb4a809b17ffaef7d5fb8125 
https://github.com/dBiz/dBiz

**Closed** 2022-08-31 00:16 UTC
Labels: plugin
