### ISSUE TITLE
Ohmer

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/library#423] opened 2018-04-02 14:52 UTC
name: Ohmer Modules
author: Dominique Camus
license: BSD-3-Clause
contactEmail: domi.camus@free.fr
pluginUrl: https://github.com/DomiKamu/Ohmer-Modules
authorUrl: https://github.com/DomiKamu
manualUrl: https://github.com/DomiKamu/Ohmer-Modules/blob/master/README.md
sourceUrl: https://github.com/DomiKamu/Ohmer-Modules.git
donateUrl: https://www.paypal.me/DominiqueCAMUS
latestVersion: 0.6.2

**Comment by phdsg** [comment] 2018-04-02 14:54
please reuse #391
as described here: https://github.com/VCVRack/community#for-plugin-developers

**Comment by phdsg** [comment] 2018-04-02 14:54
duplicate of #391

**Comment by DomiKamu** [comment] 2018-04-02 16:28
From Plugins page it's an outdated, version (v0.6.0), five or six days later! 
Also, link to manual from Plugins page remains bad.

**Comment by DomiKamu** [comment] 2019-06-24 22:01
https://github.com/DomiKamu/Ohmer-Modules.git
Lastest commit : 3ecc772f079855ff9bccb5fe96030db4a8b19fd0
Plugin version: 1.0.0

Thanks in advance.
Dominique.

**Comment by cschol** [comment] 2019-06-24 22:32
Please use #391 for tracking.

**Closed by cschol** 2019-06-24 22:32 UTC
