### ISSUE TITLE
Qwelk

### ISSUE THREAD

**Issue by raincheque** [VCVRack/library#545] opened 2019-03-21 12:26 UTC
Hello everyone. Requesting an update for the Qwelk modules, new version is 0.6.1.
commit: f62ec1e88e6630540b9fbdcbc018653c4a7bc5a5
branch: master

**Comment by cschol** [comment] 2019-03-28 03:18
Duplicate of #442. 

Please use the original issue to announce new plugin versions. Thank you!

**Closed by cschol** 2019-03-28 03:18 UTC
Labels: plugin
